apiVersion: v1
kind: Service
metadata:
  labels:
    app: watchlist-engine
  name: watchlist-engine-service
  namespace: default
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: watchlist-engine
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
