apiVersion: v1
kind: Service
metadata:
  labels:
    app: influencer-recommendation
  name: influencer-recommendation-service
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: influencer-recommendation
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
