apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influencer-recommendation-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influencer-recommendation
    spec:
      containers:
      - name: influencer-recommendation
        image: follou/influencer-recommandation:v1
        env:
        - name: CONFIG_SOURCE
          value: "local_config"

