apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rs-update-ig-engine-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rs-update-ig-engine
    spec:
      containers:
      - name: rs-update-ig-engine
        image: 002663593173.dkr.ecr.us-east-1.amazonaws.com/follou/rs-update-ig-engine:latest
        env:
        - name: CONFIG_SOURCE
          value: "aws_config"
      imagePullSecrets:
      - name: regcred
